name: Provision DMX Core
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    env:
      AzureClientId: ${{ secrets.AZURECLIENTID }}
      AzureTenantId: ${{ secrets.AZURETENANTID }}
      AzureClientSecret: ${{ secrets.AZURECLIENTSECRET }}
      AzureAdminName: ${{ secrets.AZUREADMINNAME }}
      AzureAdminAccess: ${{ secrets.AZUREADMINACCESS }}
      AzureAdInstance: ${{ secrets.AZUREADINSTANCE }}
      AzureAdDomain: ${{ secrets.AZUREADDOMAIN }}
      AzureAdCallbackPath: ${{ secrets.AZUREADCALLBACKPATH }}
      AzureAdScopes: ${{ secrets.AZUREADSCOPES }}
      ExternalLabApiUrl: ${{ secrets.EXTERNALLABAPIURL }}
      ExternalLabApiAccessKey: ${{ secrets.EXTERNALLABAPIACCESSKEY }}
    steps:
    - name: Check Out
      uses: actions/checkout@v2
    - name: Setup Dot Net Version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.1.22110.4
        include-prerelease: true
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Provision
      run: dotnet run --project .\DMX.Core.Api.Infrastructure.Provision\DMX.Core.Api.Infrastructure.Provision.csproj
