name: Provision DMX Core
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    env:
      AzureAdAppProvisionClientId: ${{ secrets.AZURE_AD_APP_PROVISION_CLIENT_ID }}
      AzureAdAppProvisionClientSecret: ${{ secrets.AZURE_AD_APP_PROVISION_CLIENT_SECRET }}
      AzureAdAppProvisionTenantId: ${{ secrets.AZURE_TENANT_ID }}
      AzureSqlServerAdminName: ${{ secrets.AZURE_SQL_SERVER_ADMIN_NAME }}
      AzureSqlServerAdminAccess: ${{ secrets.AZURE_SQL_SERVER_ADMIN_ACCESS }}
      AzureAdDmxCoreInstance: ${{ secrets.AZURE_AD_INSTANCE }}
      AzureAdDmxCoreDomain: ${{ secrets.AZURE_AD_DOMAIN }}
      AzureAdDmxCoreCallbackPath: ${{ secrets.AZURE_AD_CALLBACK_PATH }}
      AzureAdDmxCoreScopes: ${{ secrets.AZURE_AD_SCOPES }}
      AzureAppServiceExternalLabApiUrl: ${{ secrets.AZURE_APP_SERVICE_EXTERNAL_LAB_API_URL }}
      AzureAppServiceExternalLabApiAccessKey: ${{ secrets.AZURE_APP_SERVICE_EXTERNAL_LAB_API_ACCESS_KEY }}
    steps:
    - name: Check Out
      uses: actions/checkout@v2
    - name: Setup Dot Net Version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.1.22110.4
        include-prerelease: true
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Provision
      run: dotnet run --project .\DMX.Core.Api.Infrastructure.Provision\DMX.Core.Api.Infrastructure.Provision.csproj
